### ISSUE TITLE
Installation fails with module import error

### ISSUE THREAD

**Issue by snopoke** [taxpon/pyzxcvbn#3]
The import cascade from importing `pyzxcvbn` in  `setup.py` fails when trying to import `six` which isn't yet installed.
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Gx39IK/pyzxcvbn/setup.py", line 4, in <module>
        import pyzxcvbn
      File "/tmp/pip-build-Gx39IK/pyzxcvbn/pyzxcvbn/__init__.py", line 2, in <module>
        from .main import zxcvbn
      File "/tmp/pip-build-Gx39IK/pyzxcvbn/pyzxcvbn/main.py", line 5, in <module>
        from . import matching
      File "/tmp/pip-build-Gx39IK/pyzxcvbn/pyzxcvbn/matching.py", line 6, in <module>
        from pyzxcvbn import scoring
      File "/tmp/pip-build-Gx39IK/pyzxcvbn/pyzxcvbn/scoring.py", line 8, in <module>
        from six.moves import range
    ImportError: No module named six.moves
```

**Comment by snopoke** [comment]
@nickpell FYI

**Comment by taxpon** [comment]
@snopoke I fix it. Please try pip again.
